name: ecommerce
description: FlutterShop is a premium E-commerce UI kit that you can use to build various e-commerce apps using Flutter that works on both Android & iOS. This kit contains 100+ nicely crafted minimal screens that cover everything you need for your shop app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.16.0
  animations: ^2.0.11
  url_launcher: ^6.3.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  intl: 0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  lucide_icons: ^0.257.0
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  http: ^1.4.0
  app_settings: ^6.1.1
  provider: ^6.1.5
  shimmer: ^3.0.0
  flutter_stripe: ^11.5.0
  socket_io_client: ^3.1.2
  animated_text_kit: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  firebase_messaging: ^15.2.10
  flutter_animate: ^4.5.2
  carousel_slider: ^5.1.1
  local_auth: ^2.3.0
  firebase_storage: ^12.4.10
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^4.13.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  hive_generator: ^1.1.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/animation/loganime.json
    - assets/animation/signanime.json

 