// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiu6_RfsDhLjGjalqmQ8BQxYxPPyVziA',
    appId: '1:504926840738:web:1b99963cea3f1de2ce34fb',
    messagingSenderId: '504926840738',
    projectId: 'gpal-7afcd',
    authDomain: 'gpal-7afcd.firebaseapp.com',
    storageBucket: 'gpal-7afcd.firebasestorage.app',
    measurementId: 'G-FDS2CLQDM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XQ33yI9nE6IWGts5Ydl7LFmxTBek1GE',
    appId: '1:504926840738:android:bf9550c3231de88ace34fb',
    messagingSenderId: '504926840738',
    projectId: 'gpal-7afcd',
    storageBucket: 'gpal-7afcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXfVqv-SgYu_LFJn65TajDrE2ht-nyWk',
    appId: '1:504926840738:ios:28696e91a5906383ce34fb',
    messagingSenderId: '504926840738',
    projectId: 'gpal-7afcd',
    storageBucket: 'gpal-7afcd.firebasestorage.app',
    iosClientId: '504926840738-m5ph75oa4dlqrhnfme8281j85e31ecnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPXfVqv-SgYu_LFJn65TajDrE2ht-nyWk',
    appId: '1:504926840738:ios:28696e91a5906383ce34fb',
    messagingSenderId: '504926840738',
    projectId: 'gpal-7afcd',
    storageBucket: 'gpal-7afcd.firebasestorage.app',
    iosClientId: '504926840738-m5ph75oa4dlqrhnfme8281j85e31ecnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUiu6_RfsDhLjGjalqmQ8BQxYxPPyVziA',
    appId: '1:504926840738:web:f79ddb2e722980e2ce34fb',
    messagingSenderId: '504926840738',
    projectId: 'gpal-7afcd',
    authDomain: 'gpal-7afcd.firebaseapp.com',
    storageBucket: 'gpal-7afcd.firebasestorage.app',
    measurementId: 'G-4JEB35E0RK',
  );
}
